### ISSUE TITLE
希望可以支持 NestedScrollingParent，NestedScrollingChild

### ISSUE THREAD

**Issue by idonans** [Y-bao/PullRefreshView#1]
rt. 实际生产中需要支持NestedScrolling效果，如果这个库能支持就太好了。

**Comment by Y-bao** [comment]
@idonans 谢谢你的建议 这个库本来两年前自己开发自己用的 所以可能对一些新的效果不太支持，现在托管在github 会长期维护增加新的效果

**Comment by Y-bao** [comment]
NestedScrolling

**Comment by Y-bao** [comment]
已支持 NestedScrolling 并用NestedScrolling机制重写了一个 在分支withNestedScrolling里   但是底版本 要自己实现 Listview等一些控件的NestedScrolling机制 比较麻烦 所以下一步 将非NestedScrolling实现和NestedScrolling实现相结合，高版本NestedScrolling实现 低版本转非NestedScrolling 以实现兼容

**Comment by idonans** [comment]
大神给力

**Comment by Y-bao** [comment]
2.0对NestedScrolling已经无缝支持了
