### ISSUE TITLE
执行startRefresh()方法时可以自动刷新,但是头布局不下拉显示

### ISSUE THREAD

**Issue by Dawnton** [Y-bao/PullRefreshView#5]
非常感谢作者的刷新控件,找个好久就这个最合适了,但是有个问题:在我刚进入界面时想自动执行下拉刷新的方法startRefresh(),刷新的方法是执行了,但是头布局却没有显示出来,原因不知道出在哪儿,下面是执行时打出的log:
I/flingLayout: onScrollChange:2
I/BaseHeaderView: 3
I/flingLayout: moveY:0.0
I/flingLayout: onScrollChange:0
I/BaseHeaderView: 4

希望作者帮助找出问题 谢谢!!!

**Comment by Y-bao** [comment]
`  @Override
    public void startRefresh() {
        if (pullRefreshLayout != null) {
            float moveY = pullRefreshLayout.getMoveY();
            if (moveY == 0) {
                float headerSpanHeight = getSpanHeight();
                pullRefreshLayout.startMoveTo(0, headerSpanHeight);
                setState(REFRESHING);
            }
        }
}
`
中的getSpanHeight();是要自己实现的 但是直接在getSpanHeight();中直接获取控件高度要注意 控件高度是否计算完成。
`if (headerView != null) {
            int h = headerView.getHeight();
            if (h != 0) {
                headerView.startRefresh();
            } else {
                headerView.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
                    @Override
                    public void onGlobalLayout() {
                        if (headerView.getHeight() != 0) {
                            headerView.startRefresh();
                            SDKVersionHelper.removeOnGlobalLayoutListener(headerView.getViewTreeObserver(), this);
                        }
                    }
                });
            }
        }`

如果多个页面用到 就把它封装起来

**Comment by Dawnton** [comment]
根据作者提示已经把问题解决了,非常感谢

**Comment by sionsxie** [comment]
removeOnGlobalLayoutListener这个东西只能在16以上用 怎么处理啊。。SDKVersionHelper 这个是个工具类吗？  现在我的处理方式是直接计算出来的
` @Override
    public void startRefresh() {
        if (pullRefreshLayout != null) {
            float moveY = pullRefreshLayout.getMoveY();
            if (moveY == 0) {
                float headerSpanHeight = getSpanHeight();
//                if(headerSpanHeight == 0){
//                    int w = View.MeasureSpec.makeMeasureSpec(0,View.MeasureSpec.UNSPECIFIED);
//                    int h = View.MeasureSpec.makeMeasureSpec(0,View.MeasureSpec.UNSPECIFIED);
//                    measure(w, h);
//                    headerSpanHeight = getMeasuredHeight();
//                }
                pullRefreshLayout.startMoveTo(0, headerSpanHeight);
                setState(REFRESHING);
            }
        }`
但是还有个问题就是进来调用这个方法是有明显的卡顿现象，有时会显示一小部分然后突然全部显示出来，猜测是先显示正在刷新，然后在显示刷新页面所导致的

还有是非常感谢作者提供这个库
