### ISSUE TITLE
刷新时，还能把加载拉出来，这个可以控制吗？

### ISSUE THREAD

**Issue by sionsxie** [Y-bao/PullRefreshView#7]
看代码，好像是头部和底部是分开的，不知道怎么把状态加进去。。

**Comment by Y-bao** [comment]
头部和底部 都有pullRefreshLayout 的引用
调用pullRefreshLayout的这两个函数 就可以控制
public void setHasFooter(boolean hasFooter) ；
public void setHasHeader(boolean hasHeader) ；

**Comment by pierreown** [comment]
内部 已做控制
